In [22]:
from numpy import array
nums = array([1,2,3,4,5,6,7] )

## num[:] creates only a shallow copy (explanation as below)
https://stackoverflow.com/questions/19068707/does-a-slicing-operation-give-me-a-deep-or-shallow-copy
You are creating a shallow copy, because nested values are not copied, merely referenced. A deep copy would create copies of the values referenced by the list too.

Demo:

>>> lst = [{}]
>>> lst_copy = lst[:]
>>> lst_copy[0]['foo'] = 'bar'
>>> lst_copy.append(42)
>>> lst
[{'foo': 'bar'}]
>>> id(lst) == id(lst_copy)
False
>>> id(lst[0]) == id(lst_copy[0])
True
Here the nested dictionary is not copied; it is merely referenced by both lists. The new element 42 is not shared.

Remember that everything in Python is an object, and names and list elements are merely references to those objects. A copy of a list creates a new outer list, but the new list merely receives references to the exact same objects.

A proper deep copy creates new copies of each and every object contained in the list, recursively:

>>> from copy import deepcopy
>>> lst_deepcopy = deepcopy(lst)
>>> id(lst_deepcopy[0]) == id(lst[0])
False

In [23]:
t=nums[:]

In [24]:
t

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
nums[2:]

array([3, 4, 5, 6, 7])

In [26]:
nums[:2]

array([1, 2])

In [27]:
nums[-2:]

array([6, 7])

In [28]:
nums[:-2]

array([1, 2, 3, 4, 5])

In [29]:
nums[:-2][::-1]

array([5, 4, 3, 2, 1])

In [30]:
nums[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [31]:
nums[-2:][::-1]

array([7, 6])

In [32]:
nums

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
nums[:] = nums[::-1]

In [34]:
nums[:] = nums[::-1]

In [35]:
nums[:-2] = nums[:-2][::-1]

In [36]:
nums

array([5, 4, 3, 2, 1, 6, 7])

In [37]:
nums[-2:] = nums[-2:][::-1]

In [38]:
nums

array([5, 4, 3, 2, 1, 7, 6])

In [39]:
nums[:] = nums[::-1]

In [40]:
nums

array([6, 7, 1, 2, 3, 4, 5])

In [41]:
## Solution
def rotate(nums, k):
    k = k%len(nums)
    nums[:-k] = nums[:-k][::-1]
    nums[-k:] = nums[-k:][::-1]
    nums[:] = nums[::-1]